name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Install node'
      uses: actions/setup-nodev1
    - name: 'Install NPM dependecies'
      run: npm install
    - name: 'Run code'
      run: node index.js    